audio: true
real_world: true

base_conf:
  data_path: raw_data
  mtcnn_path: mtcnn

specs:
  set_gpu: True
  gpu_num: 2

pre_process:
  dimension: 512
  model_name: 20180402-114759.pb
  piece_num: 1000

parameters:
  # video real world only have wifi data in -55 rssi
  wifi_threshold: -55
  # meeting thres -1 for all meetings
  meeting_threshold: -1
  # metric of distance in SCAN: dice or euclidean
  cdist_metric: dice
  # estimated number of victims (k)
  # audio: 23, video: 32, not real world = 50
  estimated_victims: 23
  # regularization parameter: balance the biometric feature similarity and session attendance similarity
  omega: 0.5

filter_people:
  video:
    - someone

mac_name:
  '00:00:00:00:00:00': someone